module.exports = function () {
  return {
    lineNo: 1,
    prodCode: 2010000002,
    prodName: '西游记',
    periods: '',
    prodStatus: '已保存',
    apprStatus: '未评审',
    fileStatus: '未确认',
    prodType: '图书',
    estiPrintQty: 10000,
    printAddupRatio: '',
    bindAddupRatio: '',
    prodHeight: 285,
    prodWidth: 170,
    prodThick: 35,
    frontFlapWidth: '',
    backFlapWidth: '',
    withinThick: '',
    flapUnit: 'mm',
    prodWeight: 300,
    impressionCnt: 16.5,
    prodFormat: 16,
    openType: '左翻本',
    bindType: '胶订-无线胶订',
    bindSon: '',
    ISBN: '978-7-5502-6091-7',
    BC: '1-1',
    salePrice: 30.8,
    colorStandard: 'G7',
    colormatchStandard: '样书',
    fscFlag: '否',
    greenFlag: '是',
    secretFlag: '否',
    specialDemand: '',
    filePath: '',
    qualifyLevel: 'B',
    printDiffLevel: 'B',
    bindDiffLevel: 'B',
    sourceProdId: '',
    custName: '出版社A',
    ASSISTANT: '',
    modifyerId: '',
    artPeople: '',
    routeApprDate: '',
    routeApprComment: '',
    fileApprer: '',
    apprDate: '',
    apprComment: '',
    loginTime:'',
    modifyerTime:''
  }

};
