module.exports = function () {
  return [
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    },
    {
      custAbbr: '出版社A',
      soNo: '0004',
      agentName: 'billy',
      soDate: '2016-07-15',
      dueDate: '2016-07-15',
      mercherName: 'billy',
      accpDate: '2016-07-15',
      manuCompDate: '2016-07-15',
      accpType: '抢单',
      prodNo:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      proSum:'3000',
      policyQty:'3000',
      manuStatus: '生产中',
    }
  ];
};
