module.exports = function () {
  return [
    {
      fctCode: 'no12222222',
      fctName: '盛通股份',
      prodNo: '0001',
      prodName: '西游记',
      prodType: '图书',
      qualifyLevel:'A',
      printDiffLevel: 'A',
      bindDiffLevel: 'A',
      bindType: '骑马订',
      lastPrint:'是',
      prodNum:'3000',
      spiltNum:'3000',
      prodPrice:'17500',

      orderPrice: '35000',
      send:'0',
      sendTime: '10:00',
      sendStatus: '已发',
      spiltType: '自动分配',
      accStatus:'已拒绝',
      clerk:'王鑫',
      accTime:'2016-6-5 9:00',
      refuseReason:'无法安排',
    },
    {
      fctCode: 'no12222222',
      fctName: '盛通股份',
      prodNo: '0001',
      prodName: '西游记',
      prodType: '图书',
      qualifyLevel:'A',
      printDiffLevel: 'A',
      bindDiffLevel: 'A',
      bindType: '骑马订',
      lastPrint:'是',
      prodNum:'3000',
      spiltNum:'3000',
      prodPrice:'17500',

      orderPrice: '35000',
      send:'0',
      sendTime: '10:00',
      sendStatus: '已发',
      spiltType: '自动分配',
      accStatus:'已拒绝',
      clerk:'王鑫',
      accTime:'2016-6-5 9:00',
      refuseReason:'无法安排'
    },
    {
      fctCode: 'no12222222',
      fctName: '盛通股份',
      prodNo: '0001',
      prodName: '西游记',
      prodType: '图书',
      qualifyLevel:'A',
      printDiffLevel: 'A',
      bindDiffLevel: 'A',
      bindType: '骑马订',
      lastPrint:'是',
      prodNum:'3000',
      spiltNum:'3000',
      prodPrice:'17500',

      orderPrice: '35000',
      send:'0',
      sendTime: '10:00',
      sendStatus: '已发',
      spiltType: '自动分配',
      accStatus:'已拒绝',
      clerk:'王鑫',
      accTime:'2016-6-5 9:00',
      refuseReason:'无法安排'
    }
  ];
};
