module.exports=function(){
  return [
    {
      prodCode:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      prodSum:'3000',
      prodInfoStatus:'是',
      finish:'80%',
    },
    {
      prodCode:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      prodSum:'3000',
      prodInfoStatus:'是',
      finish:'80%',
    },
    {
      prodCode:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      prodSum:'3000',
      prodInfoStatus:'是',
      finish:'80%'
    }
  ];
};
