/**
 * Created by Spring on 2016/7/20.
 */
module.exports=function(){
  return[{
      lineNo:1,
      prodCode:'0001',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      prodQty:'3000',
      prodInfoStatus:'是',
      finish:'80%'
    },
    {
      lineNo:2,
      prodCode:'0002',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      prodQty:'3000',
      prodInfoStatus:'是',
      finish:'80%'
    },
    {
      lineNo:3,
      prodCode:'0003',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      prodQty:'3000',
      prodInfoStatus:'是',
      finish:'80%'
    },
    {
      lineNo:3,
      prodCode:'0003',
      prodName:'西游记',
      prodType:'图书',
      qualifyLevel:'A',
      printDiffLevel:'A',
      bindDiffLevel:'A',
      bindType:'骑马订',
      prodQty:'3000',
      prodInfoStatus:'是',
      finish:'80%'
    }
  ];
};
